services:
  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - consul-data:/consul/data

volumes:
  consul-data:

